spring:
  application:
    name: Music-Service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: musicDatabase
      uri: mongodb://localhost:27017/musicDatabase

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  main:
    allow-bean-definition-overriding: true

  web:
    locale: fr
    locale-resolver: fixed

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  sleuth:
    sampling:
      probability: 1.0

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: music-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      mongodb:
        driver: INFO
    com:
      example:
        profiles: DEBUG
  file:
    name: logs/music-service.log

server:
  port: 8084
  servlet:
    session:
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Propriété personnalisée
custom:
  resource-path: src/main/resources/

spotify:
  api:
    client-id: c2bd86fbfe114e44a4814c65ce952698
    client-secret: 1e471c2882e94cb1baaf84426d33d9c9
    token-url: https://accounts.spotify.com/api/token
    api-url: https://api.spotify.com/v1
