apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-service
  template:
    metadata:
      labels:
        app: music-service
    spec:
      containers:
        - name: music-service
          image: koubaahm/music_service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/musicDatabase"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"